name: minio
services:
  minio:
    command:
      - server
      - /data
      - --address
      - :10000
      - --console-address
      - :10001
    container_name: minio
    expose:
      - "10000"
      - "10001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password123
      - MINIO_DOMAIN=minio
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    hostname: minio
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      timeout: 5s
      interval: 5s
      retries: 5
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - mode: ingress
        target: 10000
        published: "10000"
        protocol: tcp
      - mode: ingress
        target: 10001
        published: "10001"
        protocol: tcp
    volumes:
      - type: volume
        source: minio-data
        target: /data
        volume: {}
    networks:
      - projeto-lakehouse-1

networks:
  projeto-lakehouse-1:
    name: projeto-lakehouse-1
    external: true

volumes:
  minio-data:
    name: minio-data